<?php

namespace P3\SiteBundle\Repository;

/**
 * ExpoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpoRepository extends \Doctrine\ORM\EntityRepository
{
}
