p3_site_homepage:
    path:     /
    defaults: 
        _controller: P3SiteBundle:Site:index
p3_site_condition:
    path:     /conditions-generales-de-vente
    defaults: 
        _controller: P3SiteBundle:Site:condition
p3_site_admin:
    path:     /admin
    defaults: 
        _controller: P3SiteBundle:Site:admin
p3_site_adminsupprimer:
    path:     /admin/supprimer
    defaults: 
        _controller: P3SiteBundle:Site:supprimer
p3_site_adminsuppression:
    path:     /admin/suppression/{id}
    defaults: 
        _controller: P3SiteBundle:Site:suppression